version: '3.1'

services:
   
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - "8086:8086"
     
    networks:
      - mysensors-net
    volumes:
      - /media/files/files/MySensors/influxdb/data:/var/lib/influxdb2:rw
      - /home/richard/Containers/influxdb/config:/etc/influxdb2:rw
    # # Automatically setup influxdb
    # TODO: not tested...
    environment:
      - PUID=1000
      - PGID=1001
      - TZ=Pacific/Auckland
    #  - DOCKER_INFLUXDB_INIT_MODE=setup
    #  - DOCKER_INFLUXDB_INIT_USERNAME=richard
    #   - DOCKER_INFLUXDB_INIT_PASSWORD=my-password
    #  - DOCKER_INFLUXDB_INIT_ORG=reynoldsave
    #  - DOCKER_INFLUXDB_INIT_BUCKET=mysensors
    # # (optional) Configure Data Retention
    #   - DOCKER_INFLUXDB_INIT_RETENTION=1w
    # # (optional) Admin Token
    #   - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=my-super-secret-auth-token
    # # (optional) If you're using self-signed certs
    # command: influxd --tls-cert=/etc/ssl/cert.pem --tls-key=/etc/ssl/cert-key.pem
    
    restart: unless-stopped
    
  #telegraf:
  #  image: telegraf:latest
  #  container_name: telegraf
  #  networks:
  #    - mysensors-net
  #  links:
  #    - influxdb
  #  volumes:
  #    - /home/richard/Containers/telegraf/config/telegraf.conf:/etc/telegraf/telegraf.conf:ro
  #  depends_on:
  #    - influxdb
  #  restart: unless-stopped
      
    
networks:
  mysensors-net:
