version: "2.1"
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin
    container_name: jellyfin
    network_mode: host
    devices:
      - /dev/dri:/dev/dri
    environment:
      - PUID=1000
      - PGID=1001
      - TZ=Pacific/Auckland
      - JELLYFIN_PublishedServerUrl=192.168.1.101 #optional
    volumes:
      - /home/richard/Containers/jellyfin/config:/config
      - /nfs/TV:/data/tvshows
      - /nfs/Movies:/data/movies
      - /nfs/Music:/data/music
      - /media/files/files/homemedia:/data/homemedia
      - /media/files/Recordings:/data/recordings
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    restart: unless-stopped
